name: build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          # remove after stable version released
          npm i -g npm@7
          npm install
        env:
          CI: true

#      - name: Deploy to Vercel Staging
#        uses: amondnet/vercel-action@v20
#        with:
#          vercel-token: llsV1VdwCErPSfuCD6sAa4Xg
#          vercel-org-id: 0q88pJH74xGXoZC9yvMzTPgD
#          vercel-project-id: prj_BOoZq6QatTTgJfbRCsAMZ5KnMdka
#          working-directory: ./apps/web-client
